namespace RProvider

open System
open System.Collections.Generic

open RBridge
open RBridge.SymbolicExpression
open RBridge.Extensions
open RBridge.Extensions.ActivePatterns
open RProvider.Internal
open RProvider.Internal.RInit

/// Contains helper functions for calling the functions generated by the R provider,
/// such as the `namedParams` function for specifying named parameters.
/// The module is automatically opened when you open the `RProvider` namespace.
[<AutoOpen>]
module Helpers =

    /// Construct a dictionary of named params to pass to an R function.
    ///
    /// ## Example
    /// For example, if you want to call the `R.plot` function with named parameters
    /// specifying `x`, `type`, `col` and `ylim`, you can use the following:
    ///
    ///     [ "x", box widgets;
    ///       "type", box "o";
    ///       "col", box "blue";
    ///       "ylim", box [0; 25] ]
    ///     |> namedParams |> R.plot
    ///
    let namedParams (s: seq<string * _>) = dict <| Seq.map (fun (n, v) -> n, box v) s


/// Adds functions to the Symbolic Expression module,
/// which cover semantic operations and have the R engine
/// singleton injected in.
module SymbolicExpression =

    /// Get the R classes associated with an R expression.
    let rClass sexp =
        match SymbolicExpression.tryGetAttribute sexp "class" Singletons.engine.Value with
        | None -> [||]
        | Some attrs ->
            match attrs with
            | CharacterVector Singletons.engine.Value v -> v |> Extract.extractStringArray Singletons.engine.Value
            | _ -> [||]

    /// Pass a value from R memory space into .NET, represented
    /// as a .NET primitive or the closest approximation of the
    /// relevant R primitive.
    let getValue<'a> sexp =
        Converters.Convert.fromR<'a> Singletons.engine.Value sexp

    let getValueObj sexp =
        Converters.Convert.fromR<obj> Singletons.engine.Value sexp

    let listItem name sexp =
        SymbolicExpression.getListItemByName Singletons.engine.Value name sexp

    let getMember name sexp =
        match sexp with
        | S4Object Singletons.engine.Value s4 ->
            match SymbolicExpression.tryGetAttribute sexp name Singletons.engine.Value with
            | Some e -> e
            | None -> failwithf "Member not defined: %s" name
        | List Singletons.engine.Value l -> listItem name l
        | _ -> invalidOp "Unsupported operation on R object"

    let typedVectorByName (name:string) sexp =
        match Runtime.RTypes.Vector.tryCreate sexp with
        | Ok v -> v.[name]
        | Error msg -> invalidOp msg

    let typedVectorByIndex (index:int) sexp =
        match Runtime.RTypes.Vector.tryCreate sexp with
        | Ok v -> v.[index]
        | Error msg -> invalidOp msg


/// [omit]
[<AutoOpen>]
module SymbolicExpressionExtensions =
    
    type SymbolicExpression with
        
        member this.Class: string [] = SymbolicExpression.rClass this
        member this.FromR<'a> () = SymbolicExpression.getValue<'a> this
        member this.FromR () = SymbolicExpression.getValueObj this

        /// Get the member symbolic expression of given name.
        member this.Member(name: string) = SymbolicExpression.getMember name this

        /// Get the value from the typed vector by name.
        member this.ValueOf<'a> (name: string) : 'a = SymbolicExpression.typedVectorByName name this

        /// Get the value from an indexed vector by index.
        member this.ValueAt<'a>(index: int) : 'a = SymbolicExpression.typedVectorByIndex index this

        /// Get the first value of a vector.
        member this.First<'a>() = this.ValueAt<'a>(0)

        /// Try and get the first value of a vector, returning
        /// `None` if the `SymbolicExpression` is not a vector
        /// or an empty vector.
        member this.TryFirst<'a>() = if isVector Singletons.engine.Value this then this.ValueAt<'a>(0) |> Some else None


/// Custom operators that make composing and working with
/// R symbolic expressions easier.
module Operators =

    /// Opens a dynamic property of an R symbolic expression.
    /// Supports named lists, S4 objects, and dataframes.
    /// If a dataframe, the column is extracted by name.
    let op_Dynamic (expr:SymbolicExpression, mem:string) =
        try
            match expr with
            | ActivePatterns.S4Object Singletons.engine.Value s4 ->
                SymbolicExpression.trySlot mem s4 |> Option.get
            | ActivePatterns.DataFrame Singletons.engine.Value _ ->
                SymbolicExpression.column mem expr
            | _ -> expr.Member mem
        with 
        | :? System.ArgumentOutOfRangeException -> { ptr = Singletons.engine.Value.Api.nilValue }

    /// When calling an R function, use the => operator in a list
    /// to set a parameter: [ "someparam" => 2 ]
    let (=>) (key:string) (value:'a) = (key, box value)


/// Serialisation of R values and functions to and from strings,
/// for use in communication between the type provider and the server.
module internal Serialise =

    type RParameter = string
    type HasVarArgs = bool

    type RValue =
        | Function of RParameter list * HasVarArgs
        | Value

    /// Turn an `RValue` (which captures type information of a value or function)
    /// into a serialized string that can be spliced in a quotation
    let serializeRValue =
        function
        | RValue.Value -> ""
        | RValue.Function (pars, hasVar) ->
            let prefix = if hasVar then "1" else "0"
            prefix + if List.isEmpty pars then "" else ";" + (String.concat ";" pars)

    /// Given a string produced by `serializeRValue`, reconstruct the original RValue object
    let deserializeRValue serialized =
        if isNull serialized then
            invalidArg "serialized" "Unexpected null string"
        elif serialized = "" then
            RValue.Value
        else
            let hasVar =
                match serialized.[0] with
                | '1' -> true
                | '0' -> false
                | _ -> invalidArg "serialized" "Should start with a flag"

            let args = if serialized.Length = 1 then [] else List.ofSeq (serialized.Substring(2).Split(';'))
            RValue.Function(args, hasVar)


/// [omit]
module RInterop =

    open Serialise

    /// Determines symbol names to apply for new bindings
    /// in R, and handles execution using the RProvider singletons.
    module internal Evaluate =

        let eval (env: REnvironment.REnvironment) (expr: string) =
            Logging.logWithOutput
                Singletons.characterDevice
                (fun () ->
                    Logging.logf "eval(%s)" expr
                    Evaluate.eval expr env Singletons.engine.Value)

        /// Evaluate an expression, setting the result as the specified symbol name.
        let evalTo env (expr: string) (symbol: string) device engine =
            Logging.logWithOutput
                Singletons.characterDevice
                (fun () ->
                    Logging.logf "evalto(%s, %s)" expr symbol
                    Symbol.setSymbol symbol (Evaluate.eval expr env engine)
                )

        let exec (env:REnvironment.REnvironment) (expr: string) : unit =
            Logging.logWithOutput
                Singletons.characterDevice
                (fun () ->
                    Logging.logf "exec(%s)" expr
                    // TODO below used use instead of let. IDisposable?
                    let res = eval env expr
                    ())


    let makeSafeName (name: string) = name.Replace("_", "__").Replace(".", "_")

    let getPackages () : string [] =
        Logging.logf "Communicating with R to get packages"
        let globEnv = REnvironment.globalEnv Singletons.engine.Value
        let res =
            match Evaluate.eval globEnv ".packages(all.available=T)" with
            | CharacterVector Singletons.engine.Value v -> v |> Extract.extractStringArray Singletons.engine.Value
            | _ -> failwith "Unexpected result getting packages"
        Logging.logf "Result: %O" res
        res

    let getPackageDescription packageName : string =
        let globEnv = REnvironment.globalEnv Singletons.engine.Value
        Evaluate.eval globEnv ("packageDescription(\"" + packageName + "\")$Description")
        |> SymbolicExpression.getValue

    let getFunctionDescriptions packageName =
        let globEnv = REnvironment.globalEnv Singletons.engine.Value
        Evaluate.exec globEnv <| sprintf """rds = readRDS(system.file("Meta", "Rd.rds", package = "%s"))""" packageName
        Array.zip ((Evaluate.eval globEnv "rds$Name").FromR<string []>()) ((Evaluate.eval globEnv "rds$Title").FromR<string []>())

    let loadPackage packageName : unit =
        if not (Singletons.loadedPackages.Contains packageName) then
            let globalEnv = REnvironment.globalEnv Singletons.engine.Value
            let result = Evaluate.eval globalEnv ("require(" + packageName + ")")
            if not <| result.FromR<bool>() then
                failwithf "Loading package %s failed" packageName

            Singletons.loadedPackages.Add packageName |> ignore

    /// Determines whether an expression is a value or a function.
    /// If a function, determines which arguments are available.
    let internal bindingInfo sexp : RValue =

        match sexp with
        | Closure Singletons.engine.Value clos ->

            let formals = Function.getFormals Singletons.engine.Value clos
            let names =
                Attributes.tryNames Singletons.engine.Value formals
                |> Option.defaultValue [||]
                |> Array.toList

            let hasVarArgs = names |> List.contains "..."
            let args = names |> List.filter ((<>) "...")
            RValue.Function(args, hasVarArgs)

        | ActivePatterns.BuiltIn Singletons.engine.Value _ 
        | ActivePatterns.Special Singletons.engine.Value _ ->
            // Don't know how to reflect on builtin or special args so just do as varargs
            RValue.Function([], true)

        | RealVector Singletons.engine.Value _
        | CharacterVector Singletons.engine.Value _
        | LogicalVector Singletons.engine.Value _
        | IntegerVector Singletons.engine.Value _
        | ComplexVector Singletons.engine.Value _
        | RawVector Singletons.engine.Value _
        | List Singletons.engine.Value _ ->
            RValue.Value

        | _ ->
            Logging.logf "Ignoring name of unknown SEXP type"
            RValue.Value

    /// Get bindings representing 
    let getBindings packageName =

        // In R, a namespace is an environment
        let nsEnv = REnvironment.ofNamespace Singletons.engine.Value packageName

        let names =
            Evaluate.eval nsEnv "ls(all.names=TRUE)"
            |> Extract.extractStringArray Singletons.engine.Value

        names
        |> Array.choose (fun name ->
            match REnvironment.tryGetValue Singletons.engine.Value nsEnv name with
            | None -> None
            | Some sexp ->
                let info = bindingInfo sexp
                Some (name, Serialise.serializeRValue info)
        )

    /// Given an R environment scope, call a function given the
    /// named and unnamed arguments. 
    let callFunc
        (rEnv: REnvironment.REnvironment) 
        (fn: SymbolicExpression)
        (argsByName: seq<KeyValuePair<string, obj>>)
        (varArgs: obj [])
        : SymbolicExpression =

        let namedArgs =
            argsByName
            |> Seq.map (fun kvp -> kvp.Key, Converters.Convert.toR Singletons.engine.Value kvp.Value)
            |> Seq.toList

        let unnamedArgsOrdered =
            if isNull varArgs then
                []
            else
                varArgs
                |> Array.toList
                |> List.map (fun v -> "", Converters.Convert.toR Singletons.engine.Value v)

        let allArgs = namedArgs @ unnamedArgsOrdered
        let argsPairlist = PairList.build Singletons.engine.Value allArgs
        Evaluate.call rEnv fn argsPairlist Singletons.engine.Value

    /// Call an R function by name given a function name.
    let callFuncByName
        (rEnv: REnvironment.REnvironment)
        (packageName: string)
        (funcName: string)
        (namedArgs: seq<KeyValuePair<string,obj>>)
        (varArgs: obj array)
        : SymbolicExpression =

        let nsEnv = REnvironment.ofNamespace Singletons.engine.Value packageName
        let fn =
            REnvironment.tryGetValue Singletons.engine.Value nsEnv funcName
            |> Option.defaultWith (fun () ->
                failwithf "Function %s not found in namespace %s" funcName packageName)

        callFunc rEnv fn namedArgs varArgs

    /// Call an R function given arguments, using serialised values (i.e.
    /// from the type provider itself over a socket).
    /// Always uses the global environment.
    let call
        (packageName: string)
        (funcName: string)
        (serializedRVal: string)
        (namedArgs: obj [])
        (varArgs: obj [])
        : SymbolicExpression =

        match Serialise.deserializeRValue serializedRVal with
        | RValue.Function (paramsR, hasVarArg) ->

            if namedArgs.Length <> paramsR.Length then
                failwithf "Function %s expects %d named arguments and you supplied %d" funcName paramsR.Length namedArgs.Length

            let argsByName =
                Seq.zip paramsR namedArgs
                |> Seq.map (fun (n, v) -> KeyValuePair(n, v))

            let gEnv = REnvironment.globalEnv Singletons.engine.Value
            callFuncByName gEnv packageName funcName argsByName varArgs

        | RValue.Value ->
            let nsEnv = REnvironment.ofNamespace Singletons.engine.Value packageName
            REnvironment.tryGetValue Singletons.engine.Value nsEnv funcName
            |> Option.defaultWith (fun () -> failwithf "Value %s not found" funcName)



/// [omit]
[<AutoOpen>]
module SymbolicExpressionExtensions2 =

    open RInterop
    open Serialise
    open System.IO

    // Print by capturing the output in a registered character device
    let internal printUsingDevice print =
        Singletons.characterDevice <- Devices.Intercept.beginCapture Singletons.characterDevice
        print ()
        let result = Devices.Intercept.endCapture Singletons.characterDevice
        Singletons.characterDevice <- snd result
        fst result

    /// Print by redirecting the output to a temp file (on Mono/Mac,
    /// using character device hangs the R provider for some reason).
    /// TODO Can this be removed now on .NET 10+?
    let internal printUsingTempFile print =
        let temp = Path.GetTempFileName()

        try
            let rvalStr = Function([ "file" ], true) |> serializeRValue
            call "base" "sink" rvalStr [| temp |] [||] |> ignore
            print ()
            call "base" "sink" rvalStr [||] [||] |> ignore
            File.ReadAllText temp
        finally
            File.Delete temp


    type SymbolicExpression with
        /// Call the R print function and return output as a string
        member this.Print() : string =

            let capturer = if Configuration.isUnixOrMac () then printUsingTempFile else printUsingDevice

            capturer
                (fun () ->
                    let rvalStr = RValue.Function([ "x" ], true) |> Serialise.serializeRValue
                    RInterop.call "base" "print" rvalStr [| this |] [||] |> ignore)

