name: .NET

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore tool dependencies
      run: dotnet tool restore
    - name: Restore paket dependencies
      run: dotnet paket restore
    - name: Restore dependencies
      run: dotnet restore RProvider.sln
    - name: Restore dependencies
      run: dotnet restore RProvider.Tests.sln
    - name: Build
      run: dotnet fake build -t All
