name: .NET

on:
  push:
    branches: [ master, fix-ci ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@master
      name: Setup R environment
      with:
        r-version: '4.1.1'
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore tool dependencies
      run: dotnet tool restore
    - name: Restore paket dependencies
      run: dotnet paket restore
    - name: Restore dependencies
      run: dotnet restore RProvider.sln
    - name: Restore dependencies
      run: dotnet restore RProvider.Tests.sln
    - name: Set R_HOME environment variable
      run: |
        if [[ $RUNNER_OS == 'macOS' || $RUNNER_OS == 'Linux' ]]; then
            echo "R_HOME=$(R RHOME)" >> "$GITHUB_ENV"
        else
            echo "R_HOME=$(R RHOME)" >> "$GITHUB_ENV"
        fi
    - name: Build
      run: dotnet fake build -t All
    - name: Deploy documentation from master
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        force_orphan: true
