name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    env: 
      R_HOME: /Library/Frameworks/R.framework/Resources 

    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@v1
      name: Setup R environment
      with:
          r-version: '4.1.1'
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore tool dependencies
      run: dotnet tool restore
    - name: Restore paket dependencies
      run: dotnet paket restore
    - name: Restore dependencies
      run: dotnet restore RProvider.sln
    - name: Restore dependencies
      run: dotnet restore RProvider.Tests.sln
    - name: Build
      run: dotnet fake build -t All
    - name: Deploy documentation from master
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        force_orphan: true
    - name: Examine bin
      run: ls -r bin
    - name: Publish NuGets (if this version not published before)
      run: dotnet nuget push bin\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGETKEY }} --skip-duplicate